Repository desihub/desispec, pull requests merged in 2022-04, with the labels that each got.

#1742 Iteration limit
  py/desispec/scripts/trace_shifts.py
Labels: bug

#1750 Trace shift by default
  py/desispec/scripts/proc.py
  py/desispec/workflow/desi_proc_funcs.py
  py/desispec/workflow/procfuncs.py
Labels: cleanup

#1749 daily proc retry sbatch before giving up
  py/desispec/workflow/desi_proc_funcs.py
  py/desispec/workflow/procfuncs.py
Labels: pipeline, crash

#1753 desi_group_spectra --coadd option
  py/desispec/io/spectra.py
  py/desispec/pixgroup.py
  py/desispec/scripts/coadd_spectra.py
  py/desispec/scripts/group_spectra.py
  py/desispec/spectra.py
Labels: cleanup
