Repository desihub/desispec, pull requests merged in 2022-11, with the labels that each got.

#1893 copyprod --tiles option
  bin/copyprod
Labels: enhancement

#1898 apply timefactor scaling to nightlyflat too
  py/desispec/workflow/desi_proc_funcs.py
Labels: pipeline

#1916 poststd can't fit more cams than stdstar did
  py/desispec/io/util.py
  py/desispec/scripts/proc_tilenight.py
  py/desispec/test/test_io.py
  py/desispec/workflow/procfuncs.py
Labels: bug, pipeline, crash

#1921 Allow desi_run_night to read exposure tables missing BADCAMWORD column
  py/desispec/workflow/redshifts.py
Labels: bug
