Repository desihub/desispec, pull requests merged in 2022-02, with the labels that each got.

#1668 Refactor healpix redshifts for Fuji
  bin/desi_group_spectra
  py/desispec/io/meta.py
  py/desispec/pixgroup.py
  py/desispec/scripts/group_spectra.py
  py/desispec/scripts/healpix_redshifts.py
  py/desispec/scripts/proc.py
  py/desispec/scripts/tile_redshifts.py
  py/desispec/test/test_pixgroup.py
Labels: pipeline

#1683 Purge tilenight script
  bin/desi_purge_tilenight
Labels: enhancement

#1684 fix healpix expid bookkeeping
  py/desispec/pixgroup.py
  py/desispec/scripts/healpix_redshifts.py
Labels: bug

#1695 fix plot_spectra astropy 5 table masking
  bin/plot_spectra
Labels: crash

#1669 Fit gradients in sky brightness with a few PCA eigenspectra
  bin/plot_frame
  py/desispec/io/__init__.py
  py/desispec/io/skygradpca.py
  py/desispec/scripts/proc.py
  py/desispec/scripts/sky.py
  py/desispec/sky.py
  py/desispec/skygradpca.py
  py/desispec/workflow/desi_proc_funcs.py
Labels: WIP
